[tool.poetry]
name = "kafka_queue"
version = "0.1.0"
description = "ACA-Py Event to Kafka Bridge"
authors = ["Daniel Bluhm <dbluhm@pm.me>"]

[tool.poetry.dependencies]
python = "^3.9"
aries-cloudagent = "0.8.2-rc0"
ecdsa = "^0.16.1"
aiokafka = "^0.8.0"
pydantic = "^1.8.2"

[tool.poetry.dev-dependencies]
black = "^22.3.0"
flake8 = "^6.0.0"
pre-commit = "^2.12.1"
pytest = "^6.2.3"
pytest-asyncio = "^0.15.1"
pytest-mock = "^3.6.1"
asynctest = "0.13.0"
rope = "^0.19.0"

[build-system]
requires = ["setuptools", "poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
testpaths = [
    "tests"
]
